all:
	(cd automotive/basicmath; make)
	(cd automotive/bitcount; make)
	(cd automotive/qsort; make)
	(cd automotive/susan; make)
	(cd network/dijkstra; make)
	(cd network/patricia; make)
clean:
	(cd automotive/basicmath; make clean)
	(cd automotive/bitcount; make clean)
	(cd automotive/qsort; make clean)
	(cd automotive/susan; make clean)
	(cd network/dijkstra; make clean)
	(cd network/patricia; make clean)
