CC = $(riscvgcc)
submit = $(runqemu)
OPTLVL = -O3

#FLAGS = -DBARE_METAL -Wall $(PTLVL) -target $(TOOLCHAIN) -mcpu=$(CHIP) -mthumb --specs=nosys.specs -nostartfiles -ffreestanding -std=c99 -fomit-frame-pointer -fno-optimize-sibling-calls #-static
FLAGS = -Wall $(OPTLVL) -ffreestanding -std=c99 -fomit-frame-pointer -fno-optimize-sibling-calls -lm -lc
#LIBS = --start-group -lm -lc -lbuiltins --end-group
LIBS =  -lc -lm

#LINKDIR= -L/home/luwa/freedom-u-sdk/toolchain/lib 
#INCLIB = -I/home/luwa/freedom-u-sdk/toolchain/include 